# Generated by Django 5.0.2 on 2026-02-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مدرسه')),
                ('invitation_code', models.CharField(help_text='کد منحصربه\u200cفرد برای عضویت دانش\u200cآموزان', max_length=8, unique=True, verbose_name='کد دعوت')),
                ('normal_study_threshold', models.IntegerField(default=21600, help_text='زمان مطالعه نرمال روزانه به ثانیه', verbose_name='حد نرمال مطالعه (ثانیه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدرسه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='سوپرادمین'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'دانش\u200cآموز'), ('manager', 'مدیر')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.school', verbose_name='مدرسه'),
        ),
    ]
